### ISSUE TITLE
sim not work

### ISSUE THREAD

**Issue by Cheshkin** [xen0n/android_device_meizu_arale#15]
Hey. I use your code to build the firmware on mt6752. I do not work SIM card. Once I was able to fix it. After re-obtain the firmware sim card stopped working. I always get one and same error in the logs.

```
W / PackageManager (713): Failed to parse / system / priv-app / TeleService: Signature mismatch for shared user: SharedUserSetting {14d92fc6 android.uid.phone / 1001}
W / PackageParser (713): Unknown element under <intent-filter>: android at /system/priv-app/Telecom/Telecom.apk Binary XML file line # 236
W / PackageParser (713): Unknown element under <intent-filter>: android at /system/priv-app/Telecom/Telecom.apk Binary XML file line # 244
I / PackageManager (713): / system / priv-app / TelephonyProvider changed; collecting certs
W / PackageManager (713): Failed to parse / system / priv-app / TelephonyProvider: Signature mismatch for shared user: SharedUserSetting {14d92fc6 android.uid.phone / 1001}
D / ccci_mdinit (1) (263): Error: Fail to get modem type from nvram!
```

I ask your help. Thank you.

**Comment by xen0n** [comment]
Hi, the package signatures for `TeleService` and `TelephonyProvider` seem to be different from the system one. Is your phone dual-SIM capable?

**Comment by Cheshkin** [comment]
Hey. thanks for the answer. yes my phone dual sim. lenovo k3 note. I figured with the firmware. sim cards work. your code is fully suitable for mt6752. Also batteries code. cm have to return code indicates otherwise 360. In addition there is an error: closed conferencing, local contacts are not displayed. of the framework code / av had to fix define av media blob on l 64. I also want to tell you that for my mtk ril 64 bit firmware is not suitable libnetutils. It needs to be fixed as it does not work wifi hot spot.

**Comment by androteknikz** [comment]
Xenon.. I need help.. I ported LOS 14.1 to my device which is LTE capable but the sim card doesnt detected. Log error says

Cant get md type in nvram
