### ISSUE TITLE
CM13.0 porting progress

### ISSUE THREAD

**Issue by xen0n** [xen0n/android_device_meizu_arale#17]
## Main porting
- [x] Bringup
- [x] WiFi
- [x] Bluetooth
- [x] GPS
- [x] Sensors
- [x] Camera blob compatibility
- [x] RIL
  - [x] Blob ABI compatibility
  - [x] Redo porting of basic MTK infrastructure
  - [x] Initial attach
  - [x] Voice calls
  - [x] Data calls
  - [x] VoLTE investigations (**abandoned**)
    - [x] Blob ABI compatibility
    - [x] Framework code
- [x] SELinux
## Remaining bugs
- [x] audio recording crashes (~~libblisrc32.so~~ memcpy)
- [x] HDR photo taking freezes
- [x] video recording crashes
- [x] video playback (OpenMAX)
- [x] Screencast
- [x] Media server crash after hangup (libblisrc32.so)
- [x] Incoming calls
  - [x] native crash in libblisrc32.so
  - [x] incorrect RIL behavior (incoming call indication gets ignored somehow)

and...
- [x] Screen rotation
- [x] Power-off charging animation
- [x] Native double-tap-to-wake
## Very last remaining bugs
- [ ] Excessive battery drain by `logd`
- [ ] Proximity sensor and tap-to-wake woes
- [ ] Wi-Fi spurious disconnection
- [ ] Bluetooth stability

**Comment by xen0n** [comment]
Camera is _very_ hard to fix on MX4, due to Meizu customizing the components so extensively that the stock MTK code drop would be highly unlikely to work. After a bit of mtkcam source fixing, preview works but on actually taking photo `libcam.camnode.so` seems to indirectly cause a pure virtual function call and bring down `mediaserver`.

Going on to RIL instead...

**Comment by xen0n** [comment]
- xen0n/android_frameworks_base_mtk@c5d2d65
- xen0n/android_frameworks_opt_telephony_mtk@4d4e186

SIM card is recognized but not fully initialized; the IMS and VoLTE blobs seem to be correctly wired up from the current very limited observations.

**Comment by xen0n** [comment]
Another quick note to anyone who might be stalking :smiley: :
- xen0n/android_frameworks_opt_telephony_mtk@7f14874
- xen0n/android_device_meizu_arale@3e17752

Radio initialization now progresses until initial attach! MTK Fast Dormancy and world phone impls both seem happy... Will move on to `com.android.internal.telephony.dataconnection`.

Almost 2 am here but not going to sleep before finishing the package, sad :sleepy:

**Comment by xen0n** [comment]
Quick note: voice, SMS and cellular connectivity all worked, cleaning the code up right now and will push once I finish.

MMS is of lower priority; VoLTE needs more investigation. Currently the IMS registration requests seem to be stuck, but I'm not absolutely sure that the request blocking `RIL_CMD_PROXY_3` is indeed from the IMS stack. :crying_cat_face:

**Comment by xen0n** [comment]
A note about SELinux:

```
[    1.536497]<5> (5)[1:init]init: init started!
[    1.537898]<5> (5)[1:init]SELinux:  policydb version 30 does not match my version range 15-29
[    1.538092]<5> (5)[1:init]init: SELinux:  Could not load policy:  Invalid argument
[    1.538268]<5> (5)[1:init]init: failed to load policy: Invalid argument
[    1.538310]<5> (5)[1:init]init: Security failure; rebooting into recovery mode...
```

Apparently the Lollipop kernel couldn't load policy database built for M... let's workaround it then...

**Comment by ferhung-mtk** [comment]
It seems that you make the source more complicated.
It's a good job, but not a good idea.

**Comment by xen0n** [comment]
@ferhung-mtk Which repo do you mean? If you mean the telephony stack the modification is indeed intrusive due to my trial-and-error approach to porting, but as the branch name implies, that is not the cleaned version. I still have to carefully pick out the essential bits out and that takes time; properly separating the commits is difficult because at the beginning you generally don't know exactly what to include, but actually including something usually means a heck of a lot of compilation errors which obviously can't be tolerated in a properly authored commit. So I have to open a separate branch for experiments, and only merge the proven bits back into the supposed main branch.

On another note, probably the sources inside the `mtk` folder could use more attention; separating into own Git repos could be more elegant but I hadn't bothered to do that.

**Comment by xen0n** [comment]
Just done cleaning the telephony stack, all modifications are pushed. Doing full rebuild to verify makefiles.

NOTE: Telephony stack currently reports raw mccmnc as operator alpha, will fix shortly.

**Comment by xen0n** [comment]
Full rebuild was done, fixed some makefiles in device tree. DRM is broken currently, will fix later.

**Comment by ferhung-mtk** [comment]
About "policydb version 30 does not match my version range 15-29":

In "external/sepolicy/Android.mk", look at "POLICYVERS ?= 30"
Then force policy version to 26 as android 5.0 or other version.

And look at "external/selinux/checkpolicy/checkpolicy.c", change "n = strtol(optarg, NULL, 10);" to "n = 26;".

IT IS UNTESTED. YOU CAN TRY IT.

**Comment by xen0n** [comment]
@ferhung-mtk I've already fixed that by reverting the ioctl-related commits in sepolicy repo (which require version 30), and setting `POLICYVERS := 29` in device_common.mk (as `?=` is default value and can be overridden).

**Comment by xen0n** [comment]
Okay... it seems the IMS registration for VoLTE never really finished, and the request blocking `RIL_CMD_PROXY_3` should be from the mal daemon (don't really know what that abbreviation means). However as the baseband is not easily replaced I may have to dig a little bit more before giving up :disappointed:

**Comment by bobledeveloper** [comment]
If you need a tester i can ^^
I'm a little Resourceful so if you need help maybe i can ;D

**Comment by wojted** [comment]
no new news about porting CM 13?

**Comment by xen0n** [comment]
@wojted I'm busy with my academic work so this is paused until June, as for CM13 only camera remained (VoLTE seems nearly impossible after investigation, MTK rewrote their IMS/VoLTE logic but the corresponding baseband blob is not available. As MT6595 seemed to have support for VoLTE by looking at strings inside the baseband, this surely looks like planned obsolescence.)

**Comment by wojted** [comment]
Thank you for the quick reply. I wish you luck in your academic work. We will all wait patiently for CM 13.

**Comment by xen0n** [comment]
Thanks for @fire855's _extremely_ insightful approach to camera blob compatibility, at least still photos can be taken now! Bluetooth startup hangs are also fixed.

Some more time for shaking the remaining bugs out and we'll have CM13!

**Comment by xen0n** [comment]
SELinux should be nearly full-working now. Focusing on more AV blob compatibility bugs...

**Comment by bobledeveloper** [comment]
Good news !! Thanks for your work ;D

**Comment by mayphus** [comment]
Great! Thank you. I want to know how long can we reach the CM 13 for Meizu MX4

**Comment by xen0n** [comment]
@tangmifa After I fix all the known bugs, maybe I can finish them this month but who knows ;-)

**Comment by zh0uyawen** [comment]
thks

**Comment by xen0n** [comment]
Oh actually video recording should be all fine now; but it seems OpenMAX is severely broken, so screencasts and video playback are failing. Oh my.

**Comment by zh0uyawen** [comment]
cm13 will be  coming  soon，that's great ！thank you for your hard work！

**Comment by mayphus** [comment]
吓我一跳，还以为正放包呢

**Comment by xen0n** [comment]
For other fellow MTK Marshmallow porters:

You'll want the commits below to fix your camera and OpenMAX. Of course if you're using my trees directly then no problem!
- xen0n/android_frameworks_av_mtk@0e8649c
- xen0n/android_frameworks_av_mtk@15b8851
- xen0n/android_frameworks_av_mtk@9fd6fc6

**Comment by Hikari-no-Tenshi** [comment]
@xen0n, thanks for av commits. Now i can use stock libMtkOmxVenc (Videorecord & Screencast are working). But my blobs needs extra mtk changes for color convertion (camera produces video in blue color).

**Comment by xen0n** [comment]
Incoming calls are now working... Very silly mistake of mine. Go checkout the telephony repo for details. I'm thinking about just declaring HDR photo and screencast as known bugs and just cut a release...

**Comment by ferhung-mtk** [comment]
@xen0n good job for av commits. I used these commits from mtk four month ago. But some core i make more mistakes, i will use your commit to have a test.

**Comment by xen0n** [comment]
HDR photo taking is fixed! Quite a bit of porting here. You need the frameworks/av and frameworks/base commits. I haven't squashed them, should more CAF code enters CM and disrupts future merging, so you're going to cherry-pick for yourself.

**Comment by Hikari-no-Tenshi** [comment]
@xen0n , when You will have time, please, take a look on my commit for color converter https://github.com/ResurrectionRemix-mtk/android_frameworks_av-rr/commit/d38547c624bc5d8d773edd34e52a0d63e870d0de
On lollipop similar code was working good, but on marshmallow it makes phone stuck on bootanimation.

**Comment by ferhung-mtk** [comment]
@Hikari-no-Tenshi I think you should use the MM core of this similar commit. Or use the prebuild blobs which are from MM.

**Comment by Hikari-no-Tenshi** [comment]
@ferhung-mtk, bootloop is solved (i was need to use libcamera_client and libcameraservice compiled from source instead of prebuild).
But there is another problem. Recorder uses OMX.google.h264.encoder, that doesn't support OMX_MTK_COLOR_FormatYV12.

Logcat:
E ACodec  : [OMX.google.h264.encoder] does not support color format 2130706944
E ACodec  : [OMX.google.h264.encoder] configureCodec returning error -2147483648
E ACodec  : signalError(omxError 0x80000000, internalError -2147483648)
E MediaCodec: Codec reported err 0x80000000, actionCode 0, while in state 3
E MediaCodec: configure failed with err 0x80000000, resetting...
E StagefrightRecorder: Failed to create video encoder
E MediaRecorder: start failed: -2147483648
E CAM_VideoModule: Could not start media recorder.

Where can i get MM sources? I have only for KK & L.

**Comment by xen0n** [comment]
@Hikari-no-Tenshi I have some M sources, I'll upload the `frameworks/av` part later in the day.

**Comment by Hikari-no-Tenshi** [comment]
@xen0n Thanks.
Can You also upload frameworks/native and system/core?
Now i have working 8Mpx camera, screencast, youtube, twitch, but this blue video is killing me. On L it was more simple with color convertion.

**Comment by bobledeveloper** [comment]
In remaining bugs, all checked are fixed?

**Comment by xen0n** [comment]
@Hikari-no-Tenshi Oh, sure. I'm uploading first CM13.0 release right now, will do that in the evening (have to go out after announcing the release)

@bobledeveloper Yep they are!

**Comment by bobledeveloper** [comment]
Woah you fast like lucky luck xD

**Comment by Hikari-no-Tenshi** [comment]
Looks like all my work for porting mtk color convertion was waste of time. Recorder doesn't want to use my old KK MtkOmxVenc (it uses Google h264 encoder instead). Replacing libMtkOmxCore.so, libMtkOmxVdec.so and libMtkOmxVenc.so blobs with ones from @ferhung-mtk repo, fixes recorder blue video, but breaks Screencast and Twitch.
Is there a way to fix Screencast and Twitch wile using new libMtkOmx\* blobs?

**Comment by bobledeveloper** [comment]
I can't read any video from youtube app, my sister got a MX4 with cm12.1 it works but me with cm13 not. It's possible the bug is from the rom?

**Comment by bobledeveloper** [comment]
[url=http://www.noelshack.com/2016-25-1466865211-screenshot-20160625-163132.png][img]http://image.noelshack.com/minis/2016/25/1466865211-screenshot-20160625-163132.png[/img][/url]

**Comment by xen0n** [comment]
@Hikari-no-Tenshi Hey I finally found time to upload the sources! The code drop is a bit old (from February 2016), but that's the very first Marshmallow code drop from MTK and I haven't downloaded the latest drop yet. They are [here](https://github.com/mtkcollection)!

**Comment by xen0n** [comment]
@bobledeveloper I don't know, I would have to investigate further. The (mostly Chinese) video apps I tested all work, but I haven't tried YouTube.

**Comment by Hikari-no-Tenshi** [comment]
@xen0n Thanks!
Could You tell me where to download full MM code drop (if it's not a top secret info)?

**Comment by xen0n** [comment]
@Hikari-no-Tenshi I download them from Vanzo's server, seems the credentials are disclosed in a few places like [here](http://forum.zopomobileshop.com/thread-3600-1-1.html) (look for `vanzo_guest_0`). You could also directly ssh into the machine and see what sources are available (note some of the repos are empty). This is invaluable resource from Vanzo, please be kind using it! 😄

**Comment by Hikari-no-Tenshi** [comment]
@xen0n Can't connect. What is the name of repo that You cloned?

**Comment by xen0n** [comment]
@Hikari-no-Tenshi It's `mt6753_n351bh_tf03_toro_cc_256gbitp16d3_m_lte_3m-fdd-cs_mul_20160225`, you could search for that. Maybe the machine's connectivity is bad outside of China.

**Comment by Hikari-no-Tenshi** [comment]
Looks like they have changed password. Gives error: "Permission denied, please try again.".

**Comment by xen0n** [comment]
@Hikari-no-Tenshi No they haven't, it's still `adt$$n3`. I just logged in to check for new sources.

**Comment by Hikari-no-Tenshi** [comment]
@xen0n Strange...
Sorry for bothering You. Can You tell me how to connect properly (my email: kyryljan.serhij@gmail.com)?.

**Comment by Hikari-no-Tenshi** [comment]
@xen0n Connected...

**Comment by bobledeveloper** [comment]
Rotation doesn't work too

**Comment by Komhir** [comment]
For me Youtube work, but:
   -I have problem with connection my BT speaker. 
   -Once I had reboot, when charger was connented. 
   -Rotation doesn't work 
Thank you for your great work. I use this ROM as my daily driver :D

**Comment by xen0n** [comment]
@Komhir Rotation is already fixed and will land next release. It's true Bluetooth still needs more love, thanks for your feedback! Glad you appreciate my work. 😃

**Comment by bobledeveloper** [comment]
I'll try a factory reset again

**Comment by divyashah98** [comment]
Guys 
any fix for GPS on mediatek 6582 devices ?

**Comment by bobledeveloper** [comment]
Factory reset doesn't work i can't read YouTube video from  app, screen resolution problem

**Comment by Hikari-no-Tenshi** [comment]
Can someone tell me one thing about GPS?
On my Lenovo S650 ROW mt6582 GPS working, but third-party apps can't get access to info about sattelites In view, Connected etc. But i can view info in YGPS app, that added to my builds.
Is this SELinux problem, something with permissions to read files or other?

**Comment by divyashah98** [comment]
@Hikari-no-Tenshi 
How did u got GPS working on your mt6582 ?

**Comment by Hikari-no-Tenshi** [comment]
@divyashah98 In https://github.com/ResurrectionRemix-mtk/android_device_Lenovo_S650_ROW-rr/blob/marshmallow/rootdir/init.mt6582_common.rc search lines by keywords "gps", "mnld" and add them to your init.mt6582_common.rc or init.mt6582.rc. Copy to /system/bin mtk_agpsd, wifi2agps, to /system/lib libmnl.so, to /system/lib/hw gps.mt6582.so and to /system/xbin mnld from here https://github.com/ResurrectionRemix-mtk/android_vendor_Lenovo_S650_ROW-rr

**Comment by divyashah98** [comment]
thanks @Hikari-no-Tenshi 

LET ME TRY :+1:

**Comment by xen0n** [comment]
@aiden09 Your changes to `media_codecs.xml` turns out to be unnecessary as the problem of not being able to use the hardware-accelerated codecs was my fault: xen0n/android_frameworks_av_mtk@f177664a4b778ca508f196c12101b86c92c193fc. I don't know some nice 60fps YouTube videos and am going to fix the battery life issue instead, so could you please check the 60fps issue for me?

**Comment by aiden09** [comment]
@xen0n now it perfect. all videos with 60fps playable. Also hdr work now too. but it have little freeze near 1-2 seconds. i dunno but maybe it's normal for image creation. So two bugs are fixed:
1. 60fps video
2. HDR mode

**Comment by aiden09** [comment]
@xen0n and what do you think about FM radio. I checked init and uevent scripts and found FM radio initialization. Maybe kernel was build without FM support, anyway i will try to build FM radio and import mknod. and after create /dev/fm. will see result.

**Comment by bobledeveloper** [comment]
@aiden09 i've read your changelog, and in issue you said hdr make freeze, not for me and i've your 2016-06-29 build

**Comment by xen0n** [comment]
@aiden09 HDR photo taking naturally needs more time, presumably for internally taking multiple photos at different exposure levels for processing into a final HDR image. So I won't consider this a bug.

As for FM radio, Meizu certainly disabled them in system properties and a few more places, but I don't know if the customized MT6595 chip has the FM feature stripped out. You certainly could try integrating known-good MT6592 FM radio bits and see if it works! (MT6595 is identical to MT6592 in almost every way a 3rd-party ROM developer could think of.) This is looking more like the VoLTE case though, now you point at the possibility...

**Comment by xen0n** [comment]
Screencast fixed, the initialization may fail but just retry and it'll properly start recording. The very first recorded clip may be unplayable (0-byte-sized?), but all subsequent clips are perfect.
- xen0n/android_frameworks_native_mtk@c76948edc3898f821692e6508389035538bdd242

**Comment by xen0n** [comment]
@aiden09 I investigated into your Gello crash case and found this: CyanogenMod/android_packages_apps_Gello@2c40f6b7aea52ee1a1476998bf0eabb9e9a702f2. If you synced to the latest code then the problem should be gone (although the locale-specific search engine settings would also be gone).

**Comment by aiden09** [comment]
@xen0n, proximity sensor now work perfect too. Also i applied gello patch but it still crash. Code same in my server and CM github. As for FM. I found all nessesary libraries, app start. But FM do not play. I check logcat and seen "dev/fm no such device". I checked it. mknod created that but app say it is not found. I tried two ways to create it(using mknod binary and using exec) result is same - device not found. 
And forgot to say. Now youtube videos play perfect via youtube app, but do not play via chrome browser. Other video service play video perfectly but not youtube

**Comment by aiden09** [comment]
and please apply it to fix build telephony provider http://review.cyanogenmod.org/#/c/151464/2/src/java/android/provider/Telephony.java

**Comment by xen0n** [comment]
@aiden09 Oh, I'll merge the patch on next source sync (July security update).

Aaaaand on proximity sensor... I'm quite confident that the proximity sensor is in a pretty bad shape. Try enabling both tap-to-wake and proximity check on wake, then do the following:
- Cover the proximity sensor,
- Double-tap screen, (you should be able to see a logcat message "Proximity blocked")
- Double-tap again, (this time the gesture event is NOT fired!)
- Uncover the proximity sensor,
- Double-tap again,

And you can see how the proximity sensor badly interacts with the touchscreen. I'm still investigating the way Flyme handles this mess, but still haven't got any clue.

PS: Re-calibration after every use, or toggling on/off once more after every use, are not fixing the problem. If the proximity sensor is continually covered, re-calibration will fail and next time it'll report the distance as far (!); toggling enable status doesn't work, it'll fix the touchscreen only if the sensor is already uncovered.

**EDIT**: _"No such device" indeed means the major/minor pair is not known by the kernel, but as the feature is provided by the on-chip MT6630 module I'm not sure if simply adding back the kernel-land code is enough to unlock the feature, as the kernel has module support. I don't have time to tinker with that, though._

**Comment by xen0n** [comment]
Heads up!

I've implemented the same Home button ("circle") behavior as Flyme 5:
- single tap on the circle = Back,
- swipe-up from the circle = Home,
- swipe-up from the circle's physical side but not touching it = App switch.

You'll need the relevant commits from `frameworks/base` or you'll end up without Back and App switch!

_NOTE: the code is still WIP technically, as the parameters are all hard-coded instead of being properly initialized from `config.xml` values. You'll want to follow this thread and get notified about any updates on this._

**Comment by aiden09** [comment]
@xen0n great job. You are really genius. I will test. I found one bug after some commits in framework-av or maybe after cm sync. Browser video unplayable, and sound too

**Comment by aiden09** [comment]
Swipes work fine :HAPPY:
but in landscape mode when i press space or other keys on footer of keyboard, application hide to home screen or appear task manager.  and i really happy your work

**Comment by bobledeveloper** [comment]
I think cpu need optimisation, yesterday i was watching vids and my phone was on fire, cpu temp around 70°C.

With cm12.1 it never happened

**Comment by bobledeveloper** [comment]
I can't turn on my phone even if i disable the option in settings

**Comment by aiden09** [comment]
i found bug in vp9 codec.  for example i want to watch youtube video from chrome browser. and if video is in vp9 codec then video crash. i tried to found solution in other mtk forks but it have not solutioms too. some thing wrong in decode buffer.here part of log.

`07-08 12:04:19.660 W/ACodec  (5811): [OMX.MTK.VIDEO.DECODER.VP9] setting nBufferCountActual to 13 failed: -2147483648`

**Comment by bobledeveloper** [comment]
Revert back to cm12.1 wifi too laggy, can't read youtube video 3/5 times error, proximity sensor is very buggy, battery like gasoil in my car ;D.

But your work is AMAZING THANK YOU, when other release i'll test quickly ^^

**Comment by vufa** [comment]
@xen0n When I compile the libmtkabi.so for another mtk device,there are some errors:

```
..out/../obj/SHARED_LIBRARIES/libmtkabi_intermediates/mtk_parcel.o: In function `android::Parcel::writeString16(unsigned short const*, unsigned int)':
..device/../libmtkabi/mtk_parcel.cpp:20: undefined reference to `android::Parcel::writeString16(char16_t const*, unsigned int)'
..out/../obj/SHARED_LIBRARIES/libmtkabi_intermediates/mtk_string.o: In function `android::String16::String16(unsigned short const*, unsigned int)':
..device/../libmtkabi/mtk_string.cpp:19: undefined reference to `android::String16::String16(char16_t const*, unsigned int)'
..out/../obj/SHARED_LIBRARIES/libmtkabi_intermediates/mtk_string.o: In function `android::String16::setTo(unsigned short const*, unsigned int)':
..device/../libmtkabi/mtk_string.cpp:24: undefined reference to `android::String16::setTo(char16_t const*, unsigned int)'
```

How to deal with these mistakes?

**Comment by nofearnohappy** [comment]
libmtkabi.so It is not going under ARCH64

**Comment by nofearnohappy** [comment]
libion_mtk.so also

**Comment by nofearnohappy** [comment]
Native (It takes off a lot of mistakes)

**Comment by Appendme** [comment]
Hi, accidentally come across such a problem? Device Lenovo X2EU(MT6595m)
09-07 12:32:19.071  4078  4078 D RILD    : **RIL Daemon Started**
09-07 12:32:19.071  4078  4078 D RILD    : **RILd param count=1**
09-07 12:32:19.080  4078  4078 E RILD    : RIL_Init not defined or exported in /system/lib/mtk-ril.so

**Comment by fire855** [comment]
You are starting rild.. That's why you get the error. You need to use mtkrild.

**Comment by Appendme** [comment]
> You need to use mtkrild.
Can you help with this?
RIL_SAP_Init not defined or exported in /system/lib/libreference-ril.so: undefined symbol: RIL_SAP_Init
RIL_register: version 11 is too new, max version is 10
full log https://gist.github.com/Appendme/b2453a01484fbc0493dd12325cf80b04

**Comment by Pablito2020** [comment]
@xen0n how can you think that we can fix the battery drain problem.....
Which framework is the responsable of this?
Know that you are working on cm14 now, but I would like to know to try to fix it by myself.

**Comment by anomalchik** [comment]
@xen0n Hi. 
Have you encountered a similar problem?

```
E BufferQueueProducer: [com.android.settings/com.android.settings.Settings] allocateBuffers: slot 2 without buffer is not FREE
10-09 18:34:09.475   275   329 D IMGSRV  : gralloc_device_alloc:1020: hnd=0x7fb5709b40 ID=4668 fd=47 ref=0 1080(1088)x1920-0x1 usage=0xb00 size=8355840(8355840) cache=0
10-09 18:34:09.475  1168  2196 D IMGSRV  : gralloc_register_buffer:1325: hnd=0x7f60237840 ID=4668 fd=49 ref=1
10-09 18:34:09.508   781   822 E Accel   : AccelerationSensor: unknown event (type=2, code=6)
10-09 18:34:09.508   781   822 E Accel   : AccelerationSensor: unknown event (type=2, code=7)
10-09 18:34:09.519   781   801 I ActivityManager: Displayed com.android.settings/.Settings: +294ms
10-09 18:34:09.541   275   329 D IMGSRV  : gralloc_device_free:1175: ID=4667 ref=0
10-09 18:34:09.542   275   329 D IMGSRV  : gralloc_device_free:1175: ID=4665 ref=0
10-09 18:34:09.543   275   329 D IMGSRV  : gralloc_device_alloc:1020: hnd=0x7fb25d3400 ID=4700 fd=39 ref=0 1080(1088)x1920-0x1 usage=0xb00 size=8355840(8355840) cache=0
10-09 18:34:09.543  1168  2196 D IMGSRV  : gralloc_unregister_buffer:1440: ID=4668 ref=0
10-09 18:34:09.544  1168  2196 D IMGSRV  : gralloc_register_buffer:1325: hnd=0x7f60237840 ID=4700 fd=51 ref=1
10-09 18:34:09.544  1168  2196 E IMGSRV  : :0: gralloc_module_get_buffer_params: Cannot map buffer ID=4668 before register (0x0)
10-09 18:34:09.544  1168  2196 E IMGSRV  : :0: gralloc_module_get_buffer_params: Cannot map buffer ID=4668 before register (0x0)
10-09 18:34:09.545  1168  2196 E IMGSRV  : :0: gralloc_module_get_buffer_params: Cannot map buffer ID=4668 before register (0x0)
10-09 18:34:09.546  1168  2196 E IMGSRV  : :0: gralloc_module_get_buffer_params: Cannot map buffer ID=4668 before register (0x0)
10-09 18:34:09.547  1168  2196 E IMGSRV  : :0: gralloc_module_update_last_fence: Failed to look up ID=4668
10-09 18:34:09.547  1168  2196 E IMGSRV  : :0: QueueCancelBufferWrapper: Failed to update last fence for buffer ID=4668 (-22)
10-09 18:34:09.547  1168  2196 W OpenGLRenderer: swapBuffers encountered EGL_BAD_SURFACE on 0x7f60d57340, halting rendering...
```

This causes hang framebuffer in applications. We build cm13 for mt6795. I decided to ask you since 6595 also has PowerVR

**Comment by xen0n** [comment]
@Pablito2020 Maybe by filtering out excessive MTK log messages in `liblog.so`, that'll reduce context switches and lead to generally better performance, but I don't really know. The kernel source is out of reach so not much can be done kernel side, unfortunately.

@anomalchik I don't know, maybe I have met that bug but I don't quite remember. My latest (October) build of CM13 had so many freezes and crashes that I had to withdraw its release, but the crashes seem not related to yours. 😕

**Comment by Appendme** [comment]
@xen0n can you suggest how to solve this problem?

> [gsm0710muxd] 1643:gsm0710_base_buffer_get_frame(): Get a complete frame. ch:2, ctrl:239, len:14
> [gsm0710muxd] 2383:extract_frames(): Writing 14 byte frame received on channel 2 to /dev/pts/2
> [gsm0710muxd] 2403:extract_frames(): write() returned. Written 14/14 bytes of frame to /dev/pts/2
> [gsm0710muxd] 2408:extract_frames(): fsync() failed (-1, 22 - Invalid argument)
> [gsm0710muxd] 1643:gsm0710_base_buffer_get_frame(): Get a complete frame. ch:26, ctrl:115, len:0
> [gsm0710muxd] 2557:extract_frames(): Logical channel 26 opened

https://github.com/Appendme/android_device_lenovo_x2/issues/1#issuecomment-253108331

**Comment by xen0n** [comment]
@Appendme Sorry for the late reply. I'm very busy with academics recently and may take some time to read your logs. But have you tried stock `gsm0710muxd` instead of compiled one?

**Comment by Appendme** [comment]
> But have you tried stock gsm0710muxd instead of compiled one?

@xen0n thanks you. 
gsm0710muxd now work https://gist.github.com/Appendme/02183a8d62a5f7242a2e5794f38ea0b9

But what to do with baseband?

![screenshot_20161013-002048 1](https://cloud.githubusercontent.com/assets/13421947/19320383/37640952-90db-11e6-8402-c081769636c6.png)

**Comment by xen0n** [comment]
@Appendme Glad that random guess worked! 😆 As for the baseband, it may well be the Java framework's fault, check `getprop` output for RIL-layer status. If `getprop` shows correct information, then it's `frameworks/opt/telephony` to fix. But again all MT6595 devices should be identical at least from a baseband's view...

**Comment by Appendme** [comment]
Problem with gsm0710muxd has been in use SHARE_MODEM_SUPPORT=1.
getprop:
stock:
https://gist.github.com/Appendme/f812b55a9547ebc5963dd514a3a09581
[gsm.version.ril-impl]: [mtk ril w10.20]
custom:
https://gist.github.com/Appendme/741524ef07d9414ea2b5c5e734d7ca54
[gsm.version.ril-impl]: [mtk gemini ril 1.0]

https://github.com/xen0n/android_device_meizu_arale/blob/a534126eadfe22ca7630c408cf2573b0d1c1d94a/mtk/ril/mtk-ril/ril_callbacks.c#L641
It may be a problem with the fact that he sees two sim cards?

**Comment by afaulkner420** [comment]
Hey...  just wondering, has anyone had issues with the color on video recording? screen shows normal color when recording but inverts them when playing them back (things are very blue)... its mt6592 soc, but not that different to mt6595... im guessing its something to do with video encoding and/or decoding... just wondering if someones come across this, or found a workaround... thanks guys!

Just to add, the issue doesnt exist in third party camera apps... its only the stock one...?

**Comment by Appendme** [comment]
https://gist.github.com/Appendme/b2a8c969ae18feed1c57e2d77bc211f6
Can you suggest how to fix it?

**Comment by Appendme** [comment]
Maybe you know. Youг CM good connects to Mi band 2? Work on the 7.1 will begin in late January?

**Comment by xen0n** [comment]
The bluetooth is flaky at best. Sporadic connection failures that I have no interest in fixing.

I'm busy with study and will not come back until maybe June when I'll be graduating from school, sorry.

**Comment by DeckerSU** [comment]
Hi, all ... need your advice how to fix video recording on CM13.0 / MT6737M. Problem description and full logs is available here - https://github.com/DeckerSU/video_recording_problem_cm13 , if somebody have time to look - I will be grateful. Thx in advance.

**p.s.** I was applied [this patch](https://github.com/xen0n/android_frameworks_av_mtk/commit/0e8649c) and camera with standart google.h264.encoder starts to shoot video and don't crash. But have a mistake with color conversion Red <--> Blue. So, questions are:

a) How to fix color conversion when using google.h264.encoder for video recording.
b) How to make OMX.MTK.VIDEO.ENCODER.AVC works?

**Comment by DeckerSU** [comment]
Second question is solvet, but about first i'm very interested. If we want to use google.h264.encoder (libstagefright_soft_avcenc.so) software codec for encoding video from camera - colors R/B (Red/Blue) on recorded video still swapped. Blue is Red and Red is Blue. I found SURFACE_IS_BGR32 compiler flag in SoftVideoEncoderOMXComponent.cpp but this doesn't effect on video from camera. If we set this flag colors will swapped on screenrecording, but no on video record from Camera. It's not wonder, because camera video record don't use this code.

I continued my "investigation" and found that in video recording process OS calls ColorConverter class with the following parameters:
```
   ColorConverter::ColorConverter: 0x13 --> 0x6
   OMX_COLOR_FormatYUV420Planar -> OMX_COLOR_Format16bitRGB565
```
As i'm understand - we have YUV420P from camera and internally (why?) convert it to RGB565/ Ok, i was found convertYUV420Planar in ColorConverter.cpp and make the following changes:
```
            signed u_b = v * 409;
            signed u_g = -u * 100;
            signed v_g = -v * 208;
            signed v_r = u * 517;
```
Swap R <-> B ... After that on preview picture on video after shooting - color is Ok. But during playing - still inverted. How to implement color conversion for each encoded frame in libstagefright_soft_avcenc - i'm still don't know. May be somebody here have ideas?

**p.s.** I'm interested in how to swap R<->B colors when we using software OMX.google.h264.encoder (libstagefright_soft_avcenc.so), not MTK hardware codecs.

The main problem here, as i think, that we have YUV420Planar frames stream with swapped R<->B from camera and this stream passed directly (???) to google.h264.encoder, because stream is in accepted format. Codec needs YUV420Planar and camera give it YUV420Planar stream. In which place we can insert color convertion - i didn't know :(

**Comment by SupaSaiyajinRoze** [comment]
Can you help me with, 1080p 60fps videos lags on stock gallery app. but works perfectly on other media player like MxPlayer and VLC with SW decoder.

**Comment by AndroiableDroid** [comment]
How to fix video not recording, I have tried to record using open camera but it shown me server died and how to fix double tap not working in mt6753

**Comment by afaulkner420** [comment]
Try reverting this... 
https://github.com/LineageOS/android_frameworks_av/commit/9da10a080e77b82d58450851dc57e73e01b480a8

**Comment by ghost** [comment]
How to fix the import and export of contacts to sim?

**Comment by tribual** [comment]
On Elephone P9000 we have all running except video recording and playback of 1080p and 1080p 60fps.

You have any idea how to solve this last bigger issue?

THX
