### ISSUE TITLE
Problems on meizupshelper (ported to meizu m2)

### ISSUE THREAD

**Issue by KevinMX** [xen0n/android_device_meizu_arale#22]
我尝试在魅族魅蓝note2（运行los14.1,Android [7.1.1)上使用meizupshelper（divis1969的port版本），请问下如何让他开机自动启动以自动校准距离传感器？尝试加入meizupshelper.rc](https://github.com/divis1969/android_device_meizu_meilan2/blob/los-14.1-meilan2/meizupshelper/meizupshelper.rc)无效。
Tried to use meizupshelper on m2note(running los14.1) but cannot autorun on boot.
@Moyster

**Comment by ghost** [comment]
哎呀 x)
你不要找它吗, @kevinMX, 更好 Hgouts, 谢谢 :D

**Comment by xen0n** [comment]
我最近忙毕业找工作，很长一段时间不会出现😂😂😂😂之前都没有看到，最近确实没时间折腾移植😂

**Comment by ghost** [comment]
(sorry to bother, just ignore people talking about m2 note, I created a monster :< (good luck for your job search ;) ))
