### ISSUE TITLE
Full MT6595 source code

### ISSUE THREAD

**Issue by 3sr3v3r** [xen0n/android_device_meizu_arale#6]
Hi there Xen0n, 

Following your work on the arale! You seem to be quite active.
I've got a Zopo zp999 MT6595 device. Not sure if you've seen my comments on the Crevtor repositories.

Zopo has released the full buildable source code for the ZP999
http://global.zopomobile.com/forum/viewtopic.php?f=5&t=19218

Carliv has been working getting custom recoveries work on the zp999.
https://github.com/carliv/device_zopo_zp999

Cloned it and made it compile against the latest branch of twrp.

Haven't tested yet because the recovery image is biger (11MB) so I have to change partition layout.

Am a newbe porter so I will probably take your hard work as a starting point if you don't mind ;)

**Comment by xen0n** [comment]
Well, it's holiday in China so my rhythm has slowed down a little... I've already noticed that source drop but hasn't yet downloaded it, may do so later after holiday ends. And you're of course welcome to base your work on this repo as that's exactly why all of this is open source, good luck to you!
